### ISSUE TITLE
Setting destination directory in mibdump.py not working

### ISSUE THREAD

**Issue by frki** [etingof/pysmi#10]
Documentation specify that 
"Setting destination directory
By default mibdump.py writes pysnmp MIBs into:
$HOME/.pysnmp/mibs (on UNIX)
@HOME@PySNMP ConfigurationMIBs (on Windows)
and JSON files in current working directory.
Use –destination-directory option to change default output directory."

but when using this flag its always over written to the defaults in dstFormat if/elif  for pysnmp or json.

my solution (only tested on linux) is to define dtsDirectory = None in defaults
and then have an "if not dstDirectory" in the if/elif for pysnmp or json before setting the defaults

example:
if not dstDirectory:
        dstDirectory = os.path.expanduser("~")
        if sys.platform[:3] == 'win':
            dstDirectory = os.path.join(dstDirectory, 'PySNMP Configuration', 'mibs')
        else:
            dstDirectory = os.path.join(dstDirectory, '.pysnmp', 'mibs')

**Comment by etingof** [comment]
Thank you for your report!

Fixed in d15dc61. Please, reopen this issue if it is still not working as expected.
