### ISSUE TITLE
Certificate Error trying to install pysmi

### ISSUE THREAD

**Issue by KevC2** [etingof/pysmi#12]
When I run this command:

C:\Users\kc\AppData\Local\Programs\Python\Python36-32\Scripts>pip install -e git+https://github.com/etingof/pysmi.git
egg=pysmi

I get this error:
Obtaining pysmi from git+https://github.com/etingof/pysmi.git#egg=pysmi
  Cloning https://github.com/etingof/pysmi.git to c:\users\kc\appdata\local\programs\python\python36-32\scripts\src\p
smi
fatal: unable to access 'https://github.com/etingof/pysmi.git/': SSL certificate problem: unable to get local issuer cetificate
Command "git clone -q https://github.com/etingof/pysmi.git C:\Users\kc\AppData\Local\Programs\Python\Python36-32\Scri
ts\src\pysmi" failed with error code 128 in None

**Comment by etingof** [comment]
I guess it's a GitHub thing, no relation to pysmi.

This works for me though:

    $ pip install https://github.com/etingof/pysmi/archive/master.zip

Just as a side note: the most recent  pysmi release at PyPI is exactly the same as current master so installing from github is not much different compared to simple `pip install pysmi` at the moment.

**Comment by KevC2** [comment]
Thanks for the quick reply but....

I get bunches of errors trying to run pip install https://github.com/etingof/pysmi/archive/master.zip, here is one example:
Exception:
Traceback (most recent call last):
  File "c:\users\kc\appdata\local\programs\python\python36-32\lib\site-packages\pip\_vendor\requests\packages\urllib3\
connectionpool.py", line 595, in urlopen
    chunked=chunked)

When I try pip install pysmi I get the same Certificate error as in my original post.
Thanks for the suggestions.

**Comment by etingof** [comment]
While your first command fails for me in the same way, the rest works okay.

May be you are behind some SSL proxy?

Anyway, you can just download [master.zip](https://github.com/etingof/pysmi/archive/master.zip) with your web-browser, then run `pip install master.zip`. You may need to manually install the rest of pysmi dependencies (e.g. ply) prior to installing pysmi.

**Comment by KevC2** [comment]
Thanks.
I still get the darn SSl error.
I’ll try again in am, GTG.
Thanks Again.
Kev
