### ISSUE TITLE
more than 255 arguments

### ISSUE THREAD

**Issue by cqhan777** [etingof/pysmi#15]
codegen/pysnmp.py

Can generate python script with more than 255 arguments, which make it not working.
This happened to me on ObjectGroup().setObjects() call. But it can happen on other setObjects() calls as well.
Worked around in my case by editing the generated .py file to assign the large tuple directly to ObjectGroup.objects, which takes a tuple and happened to be public member. 
[RARITAN-PX2-PDU2-MIB.txt](https://github.com/etingof/pysmi/files/1425508/RARITAN-PX2-PDU2-MIB.txt)
Attached is the MIB file that would cause problem.  Line 71 of generated .py contains > 255 arguments.

**Comment by etingof** [comment]
Thank you for raising this issue!

The fix [is here](https://github.com/etingof/pysmi/pull/16), I'd appreciate your testing and reporting back how it worked for you. So I could merge that branch and make a release.

**Comment by cqhan777** [comment]
Thanks for resolving this so quickly. I'll test it abd let you know.


On Nov 1, 2017 5:18 PM, "Ilya Etingof" <notifications@github.com> wrote:

Thank you for raising this issue!

The fix is here <https://github.com/etingof/pysmi/pull/16>, I'd appreciate
your testing and reporting back how it worked for you. So I could merge
that branch and make a release.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/etingof/pysmi/issues/15#issuecomment-341281640>, or mute
the thread

**Comment by cqhan777** [comment]
Hi Ilya,

The fix works in my case, but I don't why it would work. From the fix, it seems that cascading setObject() would result in only the last setObject() call being effective.  

The source code for ObjectGroup class in SNMPv2_CONF.py looks like:
class ObjectGroup(MibNode):
    objects = ()
    description = ''

    def getObjects(self):
        return getattr(self, 'objects', ())

    def setObjects(self, *args):
        self.objects = args
        return self

    def getDescription(self):
        return getattr(self, 'description', '')

    def setDescription(self, v):
        self.description = v
        return self


So call the setObjects() twice would void the first call.  Did I miss something here?

Regards,
Kevin

**Comment by etingof** [comment]
Hey Kevin,

> The fix works in my case, but I don't why it would work. From the fix, it seems that cascading setObject() would result in only the last setObject() call being effective.

You are right, that's my bad!

I've reworked the pysmi implementation (b21ed4d202e235cb508395504927563ac12ba024) and added the incremental objects adding mode to pysnmp (commit [408fe6c6ac6b2c1ecf1b23082d86508ae850d89b](https://github.com/etingof/pysnmp/commit/408fe6c6ac6b2c1ecf1b23082d86508ae850d89b)).

I wonder if you could re-test those? ;-)

**Comment by cqhan777** [comment]
Hi Ilya,

    I see one potential problem: Line 412 (and others)
`append=False)`
   wonder it should be 
`append=True`

   Also I wonder if you are changing the pysnmp code, why not just add a new funciton, something like
setObjectList( object_tuple), where the tuple object is the argument instead of expand it.

```
    def setObjectsList(self, list_args):
        self.objects = list_args
        return self   
``` 

Then in codegen/pysnmp.py
```
        objStr = ', '.join(objects)
        outStr = name + ' = NotificationGroup(' + oidStr + ')' + label + '\n'
        if getattr(mibBuilder, 'version', 0) < (4, 4, 2):
            outStr += name + '.objects = (' + objStr + ')\n'
        else:
            outStr += name + 'setObjectList((' + objStr + '))\n'
```

**Comment by etingof** [comment]
> I see one potential problem: Line 412 (and others)

Indeed! Fixed in 1d7ca2073e7b991acfd6b595aabe29859b787d90.

> Also I wonder if you are changing the pysnmp code, why not just add a new funciton, something like
setObjectList( object_tuple), where the tuple object is the argument instead of expand it.

Yes, this is definitely another legitimate way.

I'm leaning towards `kwargs` because I expect that some other need for customizing those `.set*()` setters behavior may come up. Creating combinations of functions like `setObjectList`/`setObjectSomethingElse` might become tedious by some point.

Does it make sense?

Thanks!

**Comment by cqhan777** [comment]
I'm OK with it.  Thanks for fixing the problem!.

**Comment by etingof** [comment]
Merged, thank you!
