### ISSUE TITLE
Add custom CodeGen example

### ISSUE THREAD

**Issue by Kenuat** [etingof/pysmi#3]
Hi @etingof, thank you for this outstanding module and all the work you've done, it is really awesome.
I'm trying to use pysmi to write my own converter to very custom text file format. I've looked through the pysnmp.py file, but these 1 thousand lines is really hard to rewrite to have something workable. Is there any chance that you provide some small and very basic template/example of AbstractCodeGen child class implementation so one could have at least some starting point please?
I would be very appreciate if this is possible.

Thank you in advance,
Dmitry

**Comment by etingof** [comment]
There is the `genCode` method of code generator that is [called](https://github.com/etingof/pysmi/blob/master/pysmi/codegen/pysnmp.py#L1019) with parsed AST root. Your task is to walk the AST producing whatever code you need.

I'd propose running pysmi in a debugger braking it at `genCode` and introspecting the `AST` object.  If you investigate that and end up with some example code, I'd happily merge your work to benefit future users of this tool. ;-)

**Comment by etingof** [comment]
Here is a [experimental branch](https://github.com/etingof/pysmi/tree/json-codegen-backend) that makes pysmi turning ASN.1 MIBs into JSON documents. And here's an [example script](https://github.com/etingof/pysmi/blob/json-codegen-backend/examples/download-and-compile-smistar-mibs-into-json.py), though you could also use the mibdump tool from command-line.

My hope is that it might be easier to convert from JSON into whatever custom format you need. In case of bugs or missing features you are welcome to open a ticket or a PR.
