### ISSUE TITLE
want to print the ObjectTpye

### ISSUE THREAD

**Issue by wuyuwu0215** [etingof/pysmi#38]
```
objectType = ObjectType(ObjectIdentity('SNMPv2-MIB', 'sysDescr'), 'Linux i386')
objectType.resolveWithMib(MibViewController)
print(str(objectType))
```

The error is ：
`AttributeError: type object 'MibViewController' has no attribute 'mibBuilder'`

I just followed the example,but it failed.
Is it a problem with my enviroment?
```
from pysnmp.proto.rfc1902 import Integer32
from pysnmp.smi.rfc1902 import ObjectIdentity, ObjectType
from pysnmp.hlapi import *
from pysnmp.smi.view import *
```

**Comment by etingof** [comment]
> objectType.resolveWithMib(MibViewController)

This looks fishy - it should be a class instance, not class. Here is [the example](http://snmplabs.com/pysnmp/examples/smi/manager/browsing-mib-tree.html#mib-objects-to-pdu-var-binds).

**Comment by wuyuwu0215** [comment]
oh，thank you. 
It was solved.At first,I didn't find where to instantiate it.(*^_^*)
