### ISSUE TITLE
wrong error return value

### ISSUE THREAD

**Issue by sebkraemer** [etingof/pysmi#40]
Hi,

I have an issue with the mibdump.py too where it fails to return something non-zero if, for example, the `mibfile` file was not found or the `--mib-source` directory does not exist.
It's important for me because I use it in my build system and want to detect errors at the right spot.

**Comment by etingof** [comment]
Thanks for raising this!

So what would be the better behavior?

**Comment by sebkraemer** [comment]
I've seen _sys.exit(1)_, that would work fine.

**Comment by etingof** [comment]
Do you mean [sys.exit(1) here](https://github.com/etingof/pysmi/blob/master/scripts/mibdump.py#L362). That totally makes sense to me. Will it fix your issue?

**Comment by sebkraemer** [comment]
I don't think so. For example, I'm getting
> Created/updated MIBs: 
> Pre-compiled MIBs borrowed: 
> Up to date MIBs: 
> Missing source MIBs: foo-MIB
> Ignored MIBs: 
> Failed MIBs:

after calling `mibdump.py --mib-borrower= --destination-directory=. --mib-source=/tmp234234 foo-MIB`

.. so I believe the error originates somewhere else or is not caught in this PySmiException. The errors in the `else` branch with the verbose errors is still executed, according to the stderr output.

**Comment by sebkraemer** [comment]
This works nicely, thank you!

Depending on the wanted behaviour one could move the errors output from the `verboseFlag` part to the lower error checking part. That way, failed and missing mibs will only be logged in error case:

```
if any(x for x in processed.values() if x == 'missing'):
    exitCode = EX_MIB_MISSING
    sys.stderr.write('Missing source MIBs: %s\r\n' % ', '.join(['%s' % x for x in sorted(processed) if processed[x] == 'missing']))
 
if any(x for x in processed.values() if x == 'failed'):
    exitCode = EX_MIB_FAILED
    sys.stderr.write('Failed MIBs: %s\r\n' % ', '.join(['%s (%s)' % (x, processed[x].error) for x in sorted(processed) if processed[x] == 'failed']))
```

But that might be personal taste. Your last commit definitely fixes the return code issue :+1:

**Comment by sebkraemer** [comment]
Btw, any idea when this will show up in pip updates? I'm not familiar with the release/sync procedure.

**Comment by etingof** [comment]
I will try to push the next release later today.

**Comment by sebkraemer** [comment]
Thanks again.
