### ISSUE TITLE
Question - Why can't generate rfc1213 and other such mibs?

### ISSUE THREAD

**Issue by develorem** [etingof/pysmi#45]
As per question above, I want the JSON conversion of some foundation mibs such as rfc1213 and entity-mib. I just want the oids really, and I could hard code them, but I prefer to do it from the mibs.

The tool ignores these mibs but I can't find reasons why in the doco.

Am new to SNMP as a whole... so apologies if this is a n00b question.

**Comment by etingof** [comment]
Try the [--mib-stub](http://snmplabs.com/pysmi/mibdump.html#blacklisting-mibs) option:

    $ mibdump.py --destination-format json --mib-stub ""  RFC1213

**Comment by develorem** [comment]
That worked, thanks.
