### ISSUE TITLE
Json type does not support bits type

### ISSUE THREAD

**Issue by atlantageek** [etingof/pysmi#5]
Looks like mibdump.py conversion to json has trouble working with bit types.  
Can recreate with this:
`mibdump.py --generate-mib-texts --destination-format json DOCS-IF3-MIB`

> I get the following error
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/bin/mibdump.py", line 302, in <module>
>     ignoreErrors=ignoreErrorsFlag))
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysmi/compiler.py", line 333, in compile
>     genTexts=options.get('genTexts')
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysmi/codegen/jsondoc.py", line 735, in genCode
>     self.handlersTable[declr[0]](self, self.prepData(declr[1:]))
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysmi/codegen/jsondoc.py", line 116, in prepData
>     self.handlersTable[el[0]](self, self.prepData(el[1:]))
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pysmi/codegen/jsondoc.py", line 669, in genTypeDeclarationRHS
>     outDict['type'] = attrs['type']
> KeyError: 'type'

**Comment by etingof** [comment]
Thank you for your report! And for testing the JSON backend!

I believe this bug has been fixed in branch [mib-index-builder](https://github.com/etingof/pysmi/tree/mib-index-builder). My test with that branch does not reveal the issue you mention.

**Comment by atlantageek** [comment]
Thanks. This worked! I really appreciate the json interface. Its difficult to read mib files and sometimes you just want to scan and search the data. Youd be surprise of the lack of snmp browser support for this. Especially on a mac.

**Comment by etingof** [comment]
BTW, there is an ongoing implementation of a global index that maps things like OID subtrees to MIB files that implement them. Try, for instance: 

    mibdump.py --build-index --rebuild --destination-format json --no-mib-writes IF-MIB CISCO-MIB

A bunch of maps will end up in `./index.json`. Just in case you find that useful. ;-)
